# Generated by Django 2.1.5 on 2021-07-19 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(default=models.CharField(max_length=50), max_length=150, verbose_name='entry slug')),
                ('product_type', models.CharField(choices=[('retail', 'retail'), ('wholesale', 'wholesale'), ('custom-wholesale', 'custom-wholesale')], default='retail', help_text='No discount = Retail, Percentage-based discount = Wholesale, Custom discount = Custom', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('qty', models.IntegerField(default=0)),
                ('slug', models.CharField(blank=True, max_length=50)),
                ('r_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('w_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('w_discount', models.DecimalField(decimal_places=3, default=0.0, help_text='Ex: 10.5% discount = 0.105', max_digits=4)),
                ('c_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('c_discount', models.DecimalField(decimal_places=3, default=0.0, help_text='Ex: 10.5% discount = 0.105', max_digits=4)),
                ('supplier', models.CharField(default='---', max_length=100)),
                ('notes', models.TextField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('qty', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SellProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('qty', models.IntegerField(default=0)),
                ('r_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('w_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('w_discount', models.DecimalField(decimal_places=3, default=0.0, help_text='Ex: 10.5% discount = 0.105', max_digits=4)),
                ('c_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('c_discount', models.DecimalField(decimal_places=3, default=0.0, help_text='Ex: 10.5% discount = 0.105', max_digits=4)),
                ('notes', models.TextField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product')),
            ],
        ),
        migrations.CreateModel(
            name='SellService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('qty', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(default=models.CharField(max_length=50), max_length=150, verbose_name='entry slug')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sellservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Service'),
        ),
        migrations.AddField(
            model_name='purchaseservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Service'),
        ),
    ]
