# Generated by Django 2.1.5 on 2021-07-15 07:49

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default=models.CharField(max_length=100), max_length=150, verbose_name='Item Slug')),
                ('supplier', models.CharField(default='---', max_length=100)),
                ('purchase_date', models.DateField(unique_for_date=True)),
                ('purchase_type', models.CharField(default='wholesale', max_length=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('purchased_qty', models.IntegerField(default=0)),
                ('purchase_discount', models.DecimalField(decimal_places=3, default=0.0, help_text='Ex: 10.5% discount = 0.105', max_digits=4)),
                ('notes', models.TextField(blank=True, max_length=255)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to=core.models.PurchaseItem.thumbnail_directory)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default=models.CharField(max_length=100), max_length=150, verbose_name='Item Slug')),
                ('supplier', models.CharField(default='---', max_length=100)),
                ('sell_date', models.DateField(unique_for_date=True)),
                ('sell_type', models.CharField(max_length=10)),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sold_qty', models.IntegerField(default=0)),
                ('selling_discount', models.DecimalField(decimal_places=3, default=0.0, help_text='Ex: 10.5% discount = 0.105', max_digits=4)),
                ('notes', models.TextField(blank=True, max_length=255)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to=core.models.SellItem.thumbnail_directory)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
