# Generated by Django 2.1.5 on 2021-07-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sellitem',
            name='sell_date',
            field=models.DateField(),
        ),
    ]
