# Generated by Django 3.2.6 on 2021-08-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('retail', 'retail'), ('wholesale', 'wholesale'), ('custom-wholesale', 'custom-wholesale')], default='retail', help_text='No discount = Retail, Percentage-based discount = Wholesale, Custom discount = Custom', max_length=20),
        ),
    ]
