# Generated by Django 2.1.5 on 2021-07-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
