# Generated by Django 2.1.5 on 2021-07-15 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210715_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellitem',
            old_name='supplier',
            new_name='sold_to',
        ),
    ]
