# Generated by Django 2.1.5 on 2021-07-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210715_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase_date',
            field=models.DateField(help_text='mm/dd/yyyy'),
        ),
    ]
