# Generated by Django 2.1.5 on 2021-07-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210714_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=100, unique=True), max_length=150, verbose_name='Item Slug'),
        ),
    ]
